# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBMASK += ".*aspeed.*\.bbappend"
BBMASK += ".*aspeed.*\.bb"

BBFILE_COLLECTIONS += "fb-mmc-layer"
BBFILE_PATTERN_fb-mmc-layer = "^${LAYERDIR}/"

LAYERSERIES_COMPAT_fb-mmc-layer = "wrynose whinlatter"
BBFILE_PATTERN_IGNORE_EMPTY_fb-mmc-layer = "1"

BBFILE_PRIORITY_fb-mmc-layer = "10"

